# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql
  database: yizkor_development
  username: root
  password: root
  server: localhost

test:
  adapter: mysql
  database: yizkor_test
  username: root
  password: root
  server: localhost


production:
  adapter: mysql
  database: yizkor_production
  username: root
  password: root
  server: localhost
